---

- name: Create www catalog
  ansible.builtin.file:
    path: "{{ nginx_index_path }}"
    state: directory
    mode: '0755'

- name: Create nginx config catalog
  ansible.builtin.file:
    path: "{{ nginx_config_path }}"
    state: directory
    mode: '0755'

- name: Create project directory on the remote server
  file:
    path: "{{project_path}}"
    state: directory

- name: Copy Dockerfile to remote server
  copy:
    src: Dockerfile
    dest: "{{project_path}}"

- name: Copy over templated index.html
  ansible.builtin.template:
    # src: "{{ playbook_dir }}/vms/web_config/index.txt"
    # content: |
    #   this is text which will be copied over to the destination file
    src: index.nginx-debian.html
    dest: "{{ nginx_index_path }}"
    # remote_src: false
  register: index_file

- name: Copy over templated nginx.conf
  ansible.builtin.template:
    src: nginx.conf.j2
    dest: "{{ nginx_config_path }}"

# Uncomment if creating custom Dockerfile -->

# - name: Copy Dockerfile to remote server
#   copy:
#     src: Dockerfile
#     dest: "{{ nginx_config_path }}"

#  <---

- name: Copy docker-compose.yml to remote server
  copy:
    src: docker-compose.yml
    dest: "{{project_path}}"

- name: Check if container is running
  shell: docker ps | grep "kobenginx"
  register: container_check
  ignore_errors: yes

- name: Run Docker Compose
  shell: docker-compose up -d # --build   # <---Uncoment this arg if want to build custom image
  args:
    chdir: "{{ project_path }}"
  when: container_check.rc != 0

# - debug:
#     var: index_file
