---

# Uncomment if creating custom Dockerfile -->

# - name: Copy Dockerfile to remote server
#   copy:
#     src: Dockerfile
#     dest: "{{ nginx_config_path }}"

#  <---

- name: Copy docker-compose.yml to remote server
  copy:
    src: docker-compose.yml
    dest: "{{project_path}}"

- name: Check if container is running
  shell: docker ps | grep "kobenginx"
  register: container_check
  ignore_errors: yes

- name: Run Docker Compose
  shell: docker-compose up -d # --build   # <---Uncoment this arg if want to build custom image
  args:
    chdir: "{{ project_path }}"
  when: container_check.rc != 0

# - debug:
#     var: index_file
