---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app_name }}svc
  namespace: {{ .Values.namespace }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.app_name }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
