---
- name: Creates directory
  ansible.builtin.file:
    path: /etc/sysconfig
    state: directory

- name: Inserting template of firewall rules
  ansible.builtin.template:
    src: "{{ ansible_facts['nodename'] }}.j2"
    dest: "/etc/sysconfig/iptables"

- name: Iptables load
  ansible.builtin.shell: iptables-restore "/etc/sysconfig/iptables"
