---
- name: Creates directory
  ansible.builtin.file:
    path: /etc/iptables
    state: directory

- name: Inserting template of firewall rules
  ansible.builtin.template:
    src: "{{ ansible_facts['nodename'] }}.j2"
    dest: "/etc/iptables/rules.v4"

- name: restore firewall state from a file
  community.general.iptables_state:
    state: restored
    path: /etc/iptables/rules.v4
  async: "{{ ansible_timeout }}"
  poll: 0

# iptables-persistent
# "iptables-save > /etc/iptables/rules.v4"
