---
- name: Install the latest version of Nginx
  ansible.builtin.apt:
    name: nginx
    state: present

- import_tasks: config.yaml

- import_tasks: service.yaml

# - name: Firewall rules are setting..
#   ansible.builtin.script: ./vms/web_config/firewall.sh
