---

- name: Create www catalog
  ansible.builtin.file:
    path: "{{ nginx_index_path }}"
    state: directory
    mode: '0755'

- name: Create nginx config catalog
  ansible.builtin.file:
    path: "{{ nginx_config_path }}"
    state: directory
    mode: '0755'

- name: Copy over templated index.html
  ansible.builtin.template:
    # src: "{{ playbook_dir }}/vms/web_config/index.txt"
    # content: |
    #   this is text which will be copied over to the destination file
    src: index.nginx-debian.html
    dest: "{{ nginx_index_path }}"
    # remote_src: false
  register: index_file

- name: Copy over templated nginx.conf
  ansible.builtin.template:
    src: nginx.conf.j2
    dest: "{{ nginx_config_path }}"

- name: Create project directory on the remote server
  file:
    path: "{{project_path}}"
    state: directory
