version: '3.8'
services:
  web:
    container_name: kobenginx
    build:
      context: .
      dockerfile: Dockerfile
    image: ghcr.io/kaszebenetes/terraform:feature-docker
    ports:
      - "80:80"
    volumes:
      - /var/www/html:/var/www/html
