---
# https://docs.docker.com/engine/install/ubuntu/
- name: Uninstall conflicting packages
  ansible.builtin.package:
    name:
      - docker.io
      - docker-doc
      - docker-compose
      - docker-compose-v2
      - podman-docker
      - containerd
      - runc
    state: absent

- name: Install required packages for Docker
  ansible.builtin.package:
    name:
      - ca-certificates
      - curl
    state: present
    update_cache: yes

- name: Create directory for Docker GPG key
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: Download Docker GPG key
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /etc/apt/keyrings/docker.asc
    mode: '0644'

- name: Add Docker APT repository
  ansible.builtin.apt_repository:
    repo: "deb [arch={{ ansible_architecture }} signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    filename: docker
    state: present

- name: Update the package index with Docker packages
  apt:
    update_cache: yes

- name: Install Docker ce
  apt:
    name: docker-ce
    state: present
    update_cache: yes
    force: yes

- name: Install Docker compose
  apt:
    name: docker-compose
    state: present
    update_cache: yes
    force: yes

- name: Ensure Docker service is running
  service:
    name: docker
    state: started
    enabled: yes

- name: Add user to docker group
  user:
    name: "{{ ansible_ssh_user }}"
    groups: docker
    append: yes
  become: yes
  become_method: sudo
