---
# - hosts: all
#   gather_facts: true
#   become: true
#   tasks:
#     - debug:
#         var: hostvars[inventory_hostname]

- name: "Catch bastion ip from terraform"
  hosts: localhost
  gather_facts: false
  become: false
  tasks:
    - name: "Execute terraform output"
      shell: terraform output -raw lb_pip
      args:
        chdir: "../src/main"
      register: tf_output
      changed_when: false
    - name: "Set bastion_pip var"
      set_fact:
        bastion_pip: "{{ tf_output.stdout }}"
        # cacheable: true

- name: "Provisioning web-servers.."
  hosts: webservers
  gather_facts: true
  become: true
  vars:
    bastion_pip: "{{ hostvars['localhost'].bastion_pip }}"
  pre_tasks:
    # - debug:
    #     var: hostvars[inventory_hostname]
  roles:
    - docker
    - nginx-docker
    - nginx-docker-compose
    # - iptables

# - hosts: loadbalancers
#   gather_facts: true
#   become: true
#   vars:
#     bastion_pip: "{{ hostvars['localhost'].bastion_pip }}"
#   pre_tasks:
#     - debug:
#         msg: "Provisioning load-balancers.."
#     # - debug:
#     #     var: hostvars[inventory_hostname]
#   roles:
#     - haproxy
#     - iptables

- hosts: bastions
  gather_facts: true
  become: true
  vars:
    bastion_pip: "{{ hostvars['localhost'].bastion_pip }}"
  pre_tasks:
    - debug:
        msg: "Provisioning bastions.."
    # - debug:
    #     var: hostvars[inventory_hostname]
  roles:
    # - iptables


# - hosts: dnsservers
#   gather_facts: true
#   become: true
#   vars:
#     bastion_pip: "{{ hostvars['localhost'].bastion_pip }}"
#   pre_tasks:
#     - debug:
#         msg: "Provisioning load-balancers.."
#     # - debug:
#     #     var: hostvars[inventory_hostname]
#   roles:
#     - name: Install the latest version repository epel-release
#       ansible.builtin.apt:
#         name: epel-release
#         state: latest
#     - debug:
#         msg: "Setting up firewall rules dns-servers.."
#     - name: Firewall rules are setting..
#       ansible.builtin.script: .//vms/dns_config/firewall.sh
