---

- name: Copy Dockerfile to the remote host
  copy:
    src: ./templates/Dockerfile
    dest: /tmp/

- name: Build the Docker image
  community.docker.docker_module:
    image: nginx
    build:
      path: /tmp
      dockerfile: Dockerfile
    tag: latest

- name: Run the container
  community.docker.docker_module:
    name: nginx_container
    image: nginx:latest
    state: started
    ports:
      - "80:80"
    volumes:
      - "{{ nginx_index_path }}:{{ nginx_index_path }}"
      - "{{ nginx_config_path }}:{{ nginx_config_path }}"

- name: Copy over templated index.html
  ansible.builtin.template:
    # src: "{{ playbook_dir }}/vms/web_config/index.txt"
    # content: |
    #   this is text which will be copied over to the destination file
    src: index.nginx-debian.html
    dest: "{{ nginx_index_path }}"
    # remote_src: false
  register: index_file
  notify:
    - Restarting nginx service

# - debug:
#     var: index_file
