---

- name: Create www catalog
  ansible.builtin.file:
    path: "{{ nginx_index_path }}"
    state: directory
    mode: '0755'

- name: Create nginx config catalog
  ansible.builtin.file:
    path: "{{ nginx_config_path }}"
    state: directory
    mode: '0755'

- name: Copy over templated index.html
  ansible.builtin.template:
    # src: "{{ playbook_dir }}/vms/web_config/index.txt"
    # content: |
    #   this is text which will be copied over to the destination file
    src: index.nginx-debian.html
    dest: "{{ nginx_index_path }}"
    # remote_src: false
  register: index_file

- name: Copy over templated index.html
  ansible.builtin.template:
    src: nginx.conf.j2
    dest: "{{ nginx_config_path }}"


- name: Copy Dockerfile to the remote host
  copy:
    src: ./templates/Dockerfile
    dest: /tmp/

- name: Build image using cache source
  docker_image:
    name: web
    build:
      path: /tmp/
      dockerfile: Dockerfile
    source: build

- name: Run the container
  shell: docker run -d --name webserver -p 80:80 -v /var/www/html:/var/www/html web

# - debug:
#     var: index_file
