---
# https://docs.docker.com/engine/install/ubuntu/

- name: Install Docker prerequisites
  apt:
    name:
      - ca-certificates
      - curl
    update_cache: yes

- name: Add Docker GPG key
  copy:
    dest: /etc/apt/keyrings/docker.asc
    content: https://download.docker.com/linux/ubuntu/gpg
    mode: 0644

- name: Add Docker repository
  lineinfile:
    path: /etc/apt/sources.list.d/docker.list
    create: yes
    line: "deb [arch={{ ansible_arch }} signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu {{ ansible_distribution_major }} stable"
    # Update cache after adding the repository
    post_tasks:
      - name: Update apt cache
        apt: update_cache: yes

- name: Install Docker
  apt:
    name: docker-ce
    state: present
