---
# - hosts: all
#   gather_facts: true
#   become: true
#   tasks:
#     - debug:
#         var: hostvars[inventory_hostname]

- name: "Provisioning web-servers.."
  hosts: webservers
  gather_facts: true
  become: true
  roles:
    - nginx


- hosts: loadbalancers
  gather_facts: true
  become: true
  tasks:
    - debug:
        msg: "Provisioning load-balancers.."
    # - debug:
    #     var: hostvars[inventory_hostname]

    - name: Install the latest version of Haproxy
      ansible.builtin.apt:
        name: haproxy
        state: latest

    - name: Starting haproxy service, if it's not started
      ansible.builtin.service:
        name: haproxy
        state: started

    - name: Haproxy config setting up
      ansible.builtin.template:
        src: ./vms/lb_config/haproxy.j2
        dest: "{{ haproxy_config }}"
      register: haproxy_file
      notify:
          - Restarting harpoxy service

    - name: Firewall rules are setting..
      ansible.builtin.script: ./vms/lb_config/firewall.sh

  handlers:
    - name: Restarting harpoxy service
      systemd:
        name: nginx
        state: restarted



# - hosts: dnsservers
#   gather_facts: true
#   become: true
#   tasks:

#     - debug:
#         msg: "Provisioning dns-servers.."
#     # - debug:
#     #     var: hostvars[inventory_hostname]

#     - name: Install the latest version repository epel-release
#       ansible.builtin.apt:
#         name: epel-release
#         state: latest

#     - debug:
#         msg: "Setting up firewall rules dns-servers.."

    # - name: Firewall rules are setting..
    #   ansible.builtin.script: .//vms/dns_config/firewall.sh

- hosts: bastions
  gather_facts: true
  become: true
  tasks:

    - debug:
        msg: "Provisioning bastions.."
    # - debug:
    #     var: hostvars[inventory_hostname]

    - debug:
        msg: "Setting up firewall rules dns-servers.."

    - name: Firewall rules are setting..
      ansible.builtin.script: ./vms/bastion_config/firewall.sh
