---
name: Create and publish a Docker image - CLI

on:
  push:
    branches: ['**']
  workflow_dispatch:
    inputs:
      tagname:
        required: false
        type: string

# https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/store-information-in-variables#default-environment-variables
env:
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
  TAG_NAME: ${{ inputs.tagname || env.BRANCH_NAME }}
  REGISTRY: ghcr.io
  REGISTRY_USERNAME: ${{ github.actor }}
  REGISTRY_TOKEN: ${{ secrets.TOKEN }}
  REPO_NAME: ${{ github.repository }}
  IMAGE: "${{ env.REGISTRY }}/${{ github.repository }}:${{ env.BRANCH_NAME }}"

jobs:
  build-and-push-image:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        run: |
          echo "${{ env.REGISTRY_TOKEN }}" | docker login ${{ env.REGISTRY }} -u "${{ env.REGISTRY_USERNAME }}" --password-stdin

      - name: Verify login
        run: |
          jq '.auths | keys[]' ~/.docker/config.json | grep -i ${{ env.REGISTRY }}

      - name: Build docker image
        run: docker build ./ansible/roles/nginx-docker/templates/ -t ${{ env.IMAGE }}

      - name: Push docker image
        run: docker push ${{ env.IMAGE }}
